import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className=""
    >
      <body className={inter.className}>
        <main className="bg-black w-screen h-screen relative text-white flex flex-col">
          <nav className="flex items-center w-full bg-green-700 rounded-b-sm py-5 px-5">
            <h1 className="text-2xl">
              <Link href={"/"}>Tutorial</Link>
            </h1>
            <section className="mx-auto flex gap-5">
              <Link href={"/"}>Home</Link>
              <Link href={"/about"}>About</Link>
              <Link href={"/users"}>Users</Link>
            </section>
          </nav>

          <div className="p-5 flex-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
